from pathlib import Path
p = Path('/home/ubuntu/evently/client/src/pages/Evently.tsx')
s = p.read_text()
needle = '  const approveBooking = (booking: Booking) => { const event = events.find(item => item.id === booking.eventId); if (!event) return; const passes = Array.from({ length: booking.quantity }, () => ({ passId: createDemoPassId(), bookingId: booking.id, eventId: booking.eventId, status: "ACTIVE" as const })); saveBookings(bookings.map(item => item.id === booking.id ? { ...item, paymentStatus: "PAID", passes } : item)); toast.success("Payment approved — unique QR passes generated"); };'
replacement = needle + '\n  const [registrationFilter, setRegistrationFilter] = useState<"ALL" | "PENDING" | "PAID">("PENDING");\n  const [registrationEvent, setRegistrationEvent] = useState("ALL");\n  const [registrationSort, setRegistrationSort] = useState<"NEWEST" | "OLDEST" | "NAME">("NEWEST");\n  const visibleRegistrations = [...bookings].filter(booking => (registrationFilter === "ALL" || (booking.paymentStatus ?? "PENDING") === registrationFilter) && (registrationEvent === "ALL" || booking.eventId === registrationEvent)).sort((a, b) => registrationSort === "NAME" ? a.attendee.localeCompare(b.attendee) : registrationSort === "OLDEST" ? a.id.localeCompare(b.id) : b.id.localeCompare(a.id));'
if needle not in s:
    raise SystemExit("approval needle not found")
s = s.replace(needle, replacement, 1)
old = '<div className="mt-3 grid gap-3">{bookings.length ? bookings.map(booking => <div key={booking.id} className="flex flex-col justify-between gap-3 rounded-[14px] bg-white/70 p-3 sm:flex-row sm:items-center dark:bg-black/20"><div><div className="text-[12px] font-black">{booking.attendee} · {booking.eventTitle}</div><div className="mt-1 text-[10px] font-semibold text-[#85858d]">{booking.quantity} × {booking.ticket} · {booking.email} · {booking.paymentStatus ?? "PENDING"}</div></div>{booking.paymentStatus === "PAID" ? <span className="rounded-full bg-[#e6f6e9] px-3 py-1.5 text-[10px] font-black text-[#3f9153]">QR passes issued</span> : <button onClick={() => approveBooking(booking)} className="rounded-full bg-[#18181c] px-3 py-2 text-[10px] font-black text-white">Mark paid & issue QR</button>}</div>) : <div className="text-[12px] font-semibold text-[#85858d]">New manual registrations will appear here.</div>}</div>'
new = '<div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_1fr_auto]"><select value={registrationFilter} onChange={e => setRegistrationFilter(e.target.value as "ALL" | "PENDING" | "PAID")} className="h-10 rounded-[10px] border border-[#e7d777] bg-white/70 px-3 text-[11px] font-black dark:bg-black/20"><option value="PENDING">Pending only</option><option value="PAID">Paid only</option><option value="ALL">All registrations</option></select><select value={registrationEvent} onChange={e => setRegistrationEvent(e.target.value)} className="h-10 rounded-[10px] border border-[#e7d777] bg-white/70 px-3 text-[11px] font-black dark:bg-black/20"><option value="ALL">All events</option>{events.map(event => <option key={event.id} value={event.id}>{event.title}</option>)}</select><select value={registrationSort} onChange={e => setRegistrationSort(e.target.value as "NEWEST" | "OLDEST" | "NAME")} className="h-10 rounded-[10px] border border-[#e7d777] bg-white/70 px-3 text-[11px] font-black dark:bg-black/20"><option value="NEWEST">Newest first</option><option value="OLDEST">Oldest first</option><option value="NAME">Attendee A–Z</option></select><div className="flex h-10 items-center justify-center rounded-[10px] bg-white/60 px-3 text-[10px] font-black text-[#8d7b22] dark:bg-black/20">{visibleRegistrations.length} shown</div></div><div className="mt-3 grid gap-3">{visibleRegistrations.length ? visibleRegistrations.map(booking => <div key={booking.id} className="flex flex-col justify-between gap-3 rounded-[14px] bg-white/70 p-3 sm:flex-row sm:items-center dark:bg-black/20"><div><div className="text-[12px] font-black">{booking.attendee} · {booking.eventTitle}</div><div className="mt-1 text-[10px] font-semibold text-[#85858d]">{booking.quantity} × {booking.ticket} · {booking.email} · {booking.paymentStatus ?? "PENDING"}</div></div>{booking.paymentStatus === "PAID" ? <span className="rounded-full bg-[#e6f6e9] px-3 py-1.5 text-[10px] font-black text-[#3f9153]">QR passes issued</span> : <button onClick={() => approveBooking(booking)} className="rounded-full bg-[#18181c] px-3 py-2 text-[10px] font-black text-white">Mark paid & issue QR</button>}</div>) : <div className="rounded-[14px] bg-white/60 p-4 text-[12px] font-semibold text-[#85858d] dark:bg-black/20">No registrations match these filters.</div>}</div>'
if old not in s:
    raise SystemExit("panel needle not found")
s = s.replace(old, new, 1)
p.write_text(s)
