from pathlib import Path
p = Path('/home/ubuntu/evently/client/src/pages/Evently.tsx')
s = p.read_text()

s = s.replace('  tickets: TicketTier[];\n};', '  tickets: TicketTier[];\n  paymentUpi?: string;\n  paymentWhatsapp?: string;\n  ticketTheme?: string;\n};')
s = s.replace('  passes?: TicketPass[];\n};', '  passes?: TicketPass[];\n  paymentStatus?: "PENDING" | "PAID";\n};')
# Give mock events organizer payment details and varied ticket themes.
s = s.replace('    tickets: [\n      { name: "General Admission", price: 1499, description: "Entry + all stages", available: 386 },', '    paymentUpi: "afterglow@upi", paymentWhatsapp: "+91 98765 43210", ticketTheme: "neon",\n    tickets: [\n      { name: "General Admission", price: 1499, description: "Entry + all stages", available: 386 },')
s = s.replace('    tickets: [\n      { name: "Builder Pass", price: 2499, description: "Conference access + lunch", available: 118 },', '    paymentUpi: "productassembly@upi", paymentWhatsapp: "+91 98200 11223", ticketTheme: "cobalt",\n    tickets: [\n      { name: "Builder Pass", price: 2499, description: "Conference access + lunch", available: 118 },')
s = s.replace('    tickets: [{ name: "Workshop Seat", price: 899, description: "Materials + refreshments", available: 29 }],', '    paymentUpi: "commonground@upi", paymentWhatsapp: "+91 97654 32109", ticketTheme: "amber",\n    tickets: [{ name: "Workshop Seat", price: 899, description: "Materials + refreshments", available: 29 }],')
s = s.replace('    tickets: [{ name: "Day Pass", price: 399, description: "All stages + showcases", available: 821 }],', '    paymentUpi: "campuscreate@upi", paymentWhatsapp: "+91 99887 76655", ticketTheme: "mint",\n    tickets: [{ name: "Day Pass", price: 399, description: "All stages + showcases", available: 821 }],')
# Checkout state and booking: manual payment, not Stripe.
s = s.replace('  const [card, setCard] = useState("");\n', '  const [paymentReference, setPaymentReference] = useState("");\n')
s = s.replace('    if (!name.trim() || !email.includes("@") || card.replace(/\\s/g, "").length < 16) { toast.error("Please complete your attendee and test card details."); return; }', '    if (!name.trim() || !email.includes("@")) { toast.error("Please complete your attendee details."); return; }')
s = s.replace('const booking: Booking = { id: bookingId, eventId: event.id, eventTitle: event.title, date: event.date, location: event.location, ticket: ticket.name, quantity, total, attendee: name, email, passes: Array.from({ length: quantity }, () => ({ passId: createDemoPassId(), bookingId, eventId: event.id, status: "ACTIVE" as const })) };', 'const booking: Booking = { id: bookingId, eventId: event.id, eventTitle: event.title, date: event.date, location: event.location, ticket: ticket.name, quantity, total, attendee: name, email, paymentStatus: "PENDING", passes: [], };')
s = s.replace('toast.success("Payment successful — your ticket is ready!");', 'toast.success("Registration received — complete the manual payment steps.");')
s = s.replace('<StepTitle number="02" title="Payment" /><div className="mt-4 rounded-[16px] border border-black/[.1] bg-white p-4 dark:border-white/[.1] dark:bg-[#1c1c21]"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2 text-[12px] font-black"><div className="grid h-7 w-7 place-items-center rounded-md bg-[#635bff] text-white"><CreditCard size={14} /></div> Stripe test mode</div><div className="flex gap-1 text-[10px] font-bold text-[#8d8d95]"><ShieldCheck size={13} className="text-[#5baf6f]" /> PCI secure</div></div><label className="text-[11px] font-black text-[#73737b]">Card number</label><div className="mt-2 flex h-11 items-center gap-3 rounded-[10px] border border-black/10 px-3 dark:border-white/10"><CreditCard size={16} className="text-[#9999a1]" /><input value={card} onChange={e => setCard(e.target.value)} placeholder="4242 4242 4242 4242" inputMode="numeric" className="w-full bg-transparent text-[13px] font-semibold outline-none" /></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-[10px] border border-black/10 px-3 py-3 text-[12px] font-semibold text-[#9a9aa1] dark:border-white/10">MM / YY</div><div className="rounded-[10px] border border-black/10 px-3 py-3 text-[12px] font-semibold text-[#9a9aa1] dark:border-white/10">CVC</div></div><p className="mt-3 flex items-center gap-1.5 text-[10px] font-semibold text-[#9999a1]"><Info size={12} /> Use 4242 4242 4242 4242 for a successful test payment.</p></div>', '<StepTitle number="02" title="Manual payment" /><div className="mt-4 rounded-[16px] border border-[#e8d36a] bg-[#fffbea] p-4 dark:border-[#6b5d1e] dark:bg-[#2b281a]"><div className="flex items-center gap-2 text-[12px] font-black"><div className="grid h-7 w-7 place-items-center rounded-md bg-[#f6c945] text-[#15151a]"><CircleDollarSign size={14} /></div> Pay the organizer directly</div><p className="mt-3 text-[12px] leading-5 text-[#6f642e] dark:text-[#d8cd83]">Send exactly {money(total)} using UPI, then share the payment screenshot or reference on WhatsApp. Your QR ticket is issued after organizer approval.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-[10px] bg-white/70 p-3 dark:bg-black/20"><div className="text-[10px] font-black uppercase tracking-[.14em] text-[#9d8b2d]">UPI ID</div><div className="mt-1 font-mono text-[13px] font-black">{event.paymentUpi ?? "Organizer will share"}</div></div><div className="rounded-[10px] bg-white/70 p-3 dark:bg-black/20"><div className="text-[10px] font-black uppercase tracking-[.14em] text-[#9d8b2d]">WhatsApp</div><div className="mt-1 font-mono text-[13px] font-black">{event.paymentWhatsapp ?? "Organizer will share"}</div></div></div><Field label="Payment reference (optional)" placeholder="e.g. UPI123456" value={paymentReference} onChange={setPaymentReference} /></div>')
s = s.replace('{loading ? "Processing secure payment…" : `Pay ${money(total)}`}', '{loading ? "Submitting registration…" : "Submit registration"}')
s = s.replace('<TicketCheck size={15} className="text-[#7166e8]" /> Instant confirmation + QR ticket', '<TicketCheck size={15} className="text-[#7166e8]" /> QR ticket after manual approval')
# Create event payment fields and persist them.
s = s.replace('  const [price, setPrice] = useState(String(editing?.price ?? 999));', '  const [price, setPrice] = useState(String(editing?.price ?? 999));\n  const [paymentUpi, setPaymentUpi] = useState(editing?.paymentUpi ?? "");\n  const [paymentWhatsapp, setPaymentWhatsapp] = useState(editing?.paymentWhatsapp ?? "");')
s = s.replace('featured: false, tickets:', 'featured: false, paymentUpi, paymentWhatsapp, ticketTheme: editing?.ticketTheme ?? "custom", tickets:')
s = s.replace('<div><StepTitle number="04" title="Ticketing" />', '<div><StepTitle number="04" title="Payment & ticket identity" /><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="UPI ID" placeholder="yourname@upi" value={paymentUpi} onChange={setPaymentUpi} /><Field label="WhatsApp number" placeholder="+91 98765 43210" value={paymentWhatsapp} onChange={setPaymentWhatsapp} /></div><p className="mt-3 text-[11px] leading-5 text-[#85858d]">These details are shown to attendees at registration. After you confirm payment, Evently generates a unique QR pass with a distinct visual treatment for each participant.</p></div><div><StepTitle number="05" title="Ticketing" />')
# Organizer manual approval panel and route props.
s = s.replace('function OrganizerDashboard({ events, saveEvents }: { events: EventItem[]; saveEvents: (events: EventItem[]) => void }) {', 'function OrganizerDashboard({ events, saveEvents, bookings, saveBookings }: { events: EventItem[]; saveEvents: (events: EventItem[]) => void; bookings: Booking[]; saveBookings: (bookings: Booking[]) => void }) {')
needle = '  const deleteEvent = (id: string) => { saveEvents(events.filter(event => event.id !== id)); toast.success("Event removed from your workspace"); };'
insert = needle + '\n  const approveBooking = (booking: Booking) => { const event = events.find(item => item.id === booking.eventId); if (!event) return; const passes = Array.from({ length: booking.quantity }, () => ({ passId: createDemoPassId(), bookingId: booking.id, eventId: booking.eventId, status: "ACTIVE" as const })); saveBookings(bookings.map(item => item.id === booking.id ? { ...item, paymentStatus: "PAID", passes } : item)); toast.success("Payment approved — unique QR passes generated"); };'
s = s.replace(needle, insert)
s = s.replace('return <DashboardShell title="Organizer workspace" eyebrow="Afterglow Collective" active="Overview" role="ORGANIZER"><div', 'return <DashboardShell title="Organizer workspace" eyebrow="Afterglow Collective" active="Overview" role="ORGANIZER"><div className="mb-8 rounded-[20px] border border-[#e7d777] bg-[#fffbea] p-5 dark:border-[#6b5d1e] dark:bg-[#2b281a]"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-[#8d7b22]"><CircleDollarSign size={14} /> Manual payment approvals</div><div className="mt-3 grid gap-3">{bookings.length ? bookings.map(booking => <div key={booking.id} className="flex flex-col justify-between gap-3 rounded-[14px] bg-white/70 p-3 sm:flex-row sm:items-center dark:bg-black/20"><div><div className="text-[12px] font-black">{booking.attendee} · {booking.eventTitle}</div><div className="mt-1 text-[10px] font-semibold text-[#85858d]">{booking.quantity} × {booking.ticket} · {booking.email} · {booking.paymentStatus ?? "PENDING"}</div></div>{booking.paymentStatus === "PAID" ? <span className="rounded-full bg-[#e6f6e9] px-3 py-1.5 text-[10px] font-black text-[#3f9153]">QR passes issued</span> : <button onClick={() => approveBooking(booking)} className="rounded-full bg-[#18181c] px-3 py-2 text-[10px] font-black text-white">Mark paid & issue QR</button>}</div>) : <div className="text-[12px] font-semibold text-[#85858d]">New manual registrations will appear here.</div>}</div></div><div')
s = s.replace('if (path === "/organizer") return <OrganizerDashboard events={events} saveEvents={saveEvents} />;', 'if (path === "/organizer") return <OrganizerDashboard events={events} saveEvents={saveEvents} bookings={bookings} saveBookings={saveBookings} />;')
p.write_text(s)
